# Generated by Django 5.2.9 on 2025-12-21 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('posts', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='dropoff_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dropoff_posts', to='locations.location'),
        ),
        migrations.AddField(
            model_name='post',
            name='load_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.loadtype'),
        ),
        migrations.AddField(
            model_name='post',
            name='pickup_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_posts', to='locations.location'),
        ),
        migrations.AddField(
            model_name='post',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicletype'),
        ),
    ]
