# Generated by Django 5.2.9 on 2025-12-21 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpayment',
            name='amount',
        ),
        migrations.AddField(
            model_name='postpayment',
            name='finished_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postpayment',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='postpayment',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
