# Generated by Django 5.2.9 on 2025-12-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_remove_vehicle_driver_vehicle_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='user',
            new_name='driver',
        ),
    ]
