# Generated by Django 5.2.9 on 2025-12-30 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadtypes', '0001_initial'),
        ('vehicles', '0003_rename_user_vehicle_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('vehicle_region', 'vehicle_code', 'plate_number'), name='unique_plate_per_region_code'),
        ),
    ]
