# Generated by Django 5.2.9 on 2026-01-01 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverrating',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='driverrating',
            name='success_rate',
        ),
        migrations.AddField(
            model_name='driverrating',
            name='completed_deliveries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driverrating',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='driverrating',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
